### PR TITLE
Removed validation that deputy user must have at least one deputy ass…

### PR DESCRIPTION
**Pull request by ajkiessl**
…ignment.  Removed tests for this.

### CODE REVIEW

**Review by awead — CHANGES_REQUESTED** [review]
The shared spec is still needed to check that we can actually assign any user to the field. Also, I think you should be able to ignore the VCR changes.

**Comment by ajkiessl** [comment]
I'm going to keep the vcr changes.  I think they need to be added, but I might be missing some context around why they weren't there.

**Comment by ajkiessl** [comment]
Or maybe I'll remove them.  I haven't really used vcr.  Do you only need them if you are referencing them in a test?

**Comment by awead** [comment]
I think the VCR changes aren't relevant to the PR. We could have a mis-configured VCR setup and the yaml files are being changed when the tests are run, which shouldn't happen. If you remove the yaml changes, CI should still pass.

**Pull request merged**
