### PR TITLE
Override known dups

### PR DESCRIPTION
**Pull request by ajkiessl**
Detects non-duplicate groups when merging duplicate groups and prompts the admin if they are sure and want to proceed.

#120

### CODE REVIEW

**Comment by ajkiessl** [comment]
Still testing somethings.  Not ready to merge.

**Comment by ajkiessl** [comment]
Ok, this is ready to go.

**Review by EricDurante — APPROVED** [review]
The only thing that I would say about this that might not be obvious is that I think that it's possible for there to be a situation where you could have a duplicate group which contains some publications that belong to the same non-duplicate group, and that the non-duplicate group could have other publications in it that are not in the duplicate group. So overriding and totally deleting the non-duplicate group (as opposed to just removing the offending publications from it and then only deleting it if it's empty) in that case would remove the indicator that those other publications were determined to not be duplicates of each other. 

I can't say for sure whether or not this actually happens in practice, I just that think it's technically possible. This whole business is so mind-boggling that it's difficult to reason about it.. However, if and when such a non-duplicate group ever got deleted, probably the worst outcome would be that some similar-looking publications that aren't actually duplicates would be grouped as suspected duplicates for a second time, and an admin would have to ignore them for a second time. Probably not a huge deal.

So I haven't tried this out, but apart from that caveat above, I think the code looks good. Let's just keep that caveat in the backs of our minds so that we know what's going on if it does turn out to be an issue, and then we can address it. So feel free to merge this if you're happy with it.

**Comment by ajkiessl** [comment]
Yeah that could happen.  I think the admins would pick up on this quickly if it became common.  I'll keep this in mind in case it does.

**Pull request merged**
